[project]
name = "rent-vs-buy-calculator-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.7.0",
    "numpy>=2.3.5",
]
